spring:
  datasource:
    url:  jdbc:postgresql://localhost:5433/runmate
    username: runmate
    password: runmate
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true